// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file VariablePayloadPubSubTypes.cpp
 * This header file contains the implementation of the serialization functions.
 *
 * This file was generated by the tool fastddsgen (version: 2.1.4).
 */


#include <fastcdr/FastBuffer.h>
#include <fastcdr/Cdr.h>

#include "VariablePayloadPubSubTypes.h"

// 💡 1. LLVM이 후킹할 타겟 함수 (다시 부활!)
/*void FastCdr_serialize_memcpy(void* src, void* dest, size_t len) {
    std::memcpy(dest, src, len); 
}
*/
__attribute__((noinline))
void FastCdr_serialize_memcpy(void* src, void* dest, size_t len) {
    // LLVM Pass가 이 루프나 memcpy를 가로채서 AES로 바꿔야 합니다.
    std::memcpy(dest, src, len); 
}

using SerializedPayload_t = eprosima::fastrtps::rtps::SerializedPayload_t;
using InstanceHandle_t = eprosima::fastrtps::rtps::InstanceHandle_t;

VariablePayloadPubSubType::VariablePayloadPubSubType()
{
    setName("VariablePayload");
    auto type_size = VariablePayload::getMaxCdrSerializedSize();
    type_size += eprosima::fastcdr::Cdr::alignment(type_size, 4); /* possible submessage alignment */
    m_typeSize = static_cast<uint32_t>(type_size) + 4; /*encapsulation*/
    m_isGetKeyDefined = VariablePayload::isKeyDefined();
    size_t keyLength = VariablePayload::getKeyMaxCdrSerializedSize() > 16 ?
            VariablePayload::getKeyMaxCdrSerializedSize() : 16;
    m_keyBuffer = reinterpret_cast<unsigned char*>(malloc(keyLength));
    memset(m_keyBuffer, 0, keyLength);
}

VariablePayloadPubSubType::~VariablePayloadPubSubType()
{
    if (m_keyBuffer != nullptr)
    {
        free(m_keyBuffer);
    }
}


bool VariablePayloadPubSubType::serialize(void* data, eprosima::fastrtps::rtps::SerializedPayload_t* payload) {
    VariablePayload* vp = static_cast<VariablePayload*>(data);
    
    uint32_t is_thunk_flag = 0xDEADBEEF; 
    uint32_t real_size = vp->data().size(); 
    uint64_t func_ptr = reinterpret_cast<uint64_t>(&FastCdr_serialize_memcpy);
    uint64_t raw_data_ptr = reinterpret_cast<uint64_t>(vp->data().data());

    // 데이터 복사는 단 24바이트만 수행 (Zero-Copy 유지!)
    std::memcpy(payload->data, &is_thunk_flag, 4);
    std::memcpy(payload->data + 4, &real_size, 4);
    std::memcpy(payload->data + 8, &func_ptr, 8);
    std::memcpy(payload->data + 16, &raw_data_ptr, 8);

    // 미들웨어가 넉넉한 전송 버퍼를 할당하도록 실제 데이터 크기를 알려줍니다!
    payload->length = real_size + 24; 


    return true; 
}

// 💡 [수신부 RX] Zero-Copy TX 구조에 맞춘 수신부 업데이트
bool VariablePayloadPubSubType::deserialize(eprosima::fastrtps::rtps::SerializedPayload_t* payload, void* data) {
    VariablePayload* vp = static_cast<VariablePayload*>(data);

    // RX Crypto 플러그인이 이미 모든 헤더와 태그를 제거했습니다.
    // payload->length는 복호화된 '순수 원본 센서 데이터의 크기'와 완벽히 일치합니다!
    uint32_t real_size = payload->length;
    

    if (real_size == 0) return false;

    // 벡터 크기를 맞추고
    vp->data().resize(real_size);
    
    // 헤더 건너뛸 필요 없이, 0번지부터 그대로 복사하면 끝입니다!
    std::memcpy(vp->data().data(), payload->data, real_size);
    
    return true;
}

// 💡 4. 사이즈 제공자 (Twist의 리턴 방식과 동일하게)
std::function<uint32_t()> VariablePayloadPubSubType::getSerializedSizeProvider(void* data) {
    return [data]() -> uint32_t {
        VariablePayload* vp = static_cast<VariablePayload*>(data);
        return static_cast<uint32_t>(vp->data().size() + 24); 
    };
}

void* VariablePayloadPubSubType::createData()
{
    return reinterpret_cast<void*>(new VariablePayload());
}

void VariablePayloadPubSubType::deleteData(
        void* data)
{
    delete(reinterpret_cast<VariablePayload*>(data));
}

bool VariablePayloadPubSubType::getKey(
        void* data,
        InstanceHandle_t* handle,
        bool force_md5)
{
    if (!m_isGetKeyDefined)
    {
        return false;
    }

    VariablePayload* p_type = static_cast<VariablePayload*>(data);

    // Object that manages the raw buffer.
    eprosima::fastcdr::FastBuffer fastbuffer(reinterpret_cast<char*>(m_keyBuffer),
            VariablePayload::getKeyMaxCdrSerializedSize());

    // Object that serializes the data.
    eprosima::fastcdr::Cdr ser(fastbuffer, eprosima::fastcdr::Cdr::BIG_ENDIANNESS);
    p_type->serializeKey(ser);
    if (force_md5 || VariablePayload::getKeyMaxCdrSerializedSize() > 16)
    {
        m_md5.init();
        m_md5.update(m_keyBuffer, static_cast<unsigned int>(ser.getSerializedDataLength()));
        m_md5.finalize();
        for (uint8_t i = 0; i < 16; ++i)
        {
            handle->value[i] = m_md5.digest[i];
        }
    }
    else
    {
        for (uint8_t i = 0; i < 16; ++i)
        {
            handle->value[i] = m_keyBuffer[i];
        }
    }
    return true;
}
