// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file VariablePayload.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 2.1.4).
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "VariablePayload.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

VariablePayload::VariablePayload()
{
    // m_data com.eprosima.idl.parser.typecode.SequenceTypeCode@74ad1f1f


}

VariablePayload::~VariablePayload()
{
}

VariablePayload::VariablePayload(
        const VariablePayload& x)
{
    m_data = x.m_data;
}

VariablePayload::VariablePayload(
        VariablePayload&& x)
{
    m_data = std::move(x.m_data);
}

VariablePayload& VariablePayload::operator =(
        const VariablePayload& x)
{

    m_data = x.m_data;

    return *this;
}

VariablePayload& VariablePayload::operator =(
        VariablePayload&& x)
{

    m_data = std::move(x.m_data);

    return *this;
}

bool VariablePayload::operator ==(
        const VariablePayload& x) const
{

    return (m_data == x.m_data);
}

bool VariablePayload::operator !=(
        const VariablePayload& x) const
{
    return !(*this == x);
}

size_t VariablePayload::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    current_alignment += (1048576 * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);



    return current_alignment - initial_alignment;
}

size_t VariablePayload::getCdrSerializedSize(
        const VariablePayload& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    if (data.data().size() > 0)
    {
        current_alignment += (data.data().size() * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);
    }



    return current_alignment - initial_alignment;
}

void VariablePayload::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_data;
}

void VariablePayload::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_data;}

/*!
 * @brief This function copies the value in member data
 * @param _data New value to be copied in member data
 */
void VariablePayload::data(
        const std::vector<uint8_t>& _data)
{
    m_data = _data;
}

/*!
 * @brief This function moves the value in member data
 * @param _data New value to be moved in member data
 */
void VariablePayload::data(
        std::vector<uint8_t>&& _data)
{
    m_data = std::move(_data);
}

/*!
 * @brief This function returns a constant reference to member data
 * @return Constant reference to member data
 */
const std::vector<uint8_t>& VariablePayload::data() const
{
    return m_data;
}

/*!
 * @brief This function returns a reference to member data
 * @return Reference to member data
 */
std::vector<uint8_t>& VariablePayload::data()
{
    return m_data;
}

size_t VariablePayload::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;



    return current_align;
}

bool VariablePayload::isKeyDefined()
{
    return false;
}

void VariablePayload::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
     
}
