#pragma once
#include <cstdint>

#pragma pack(push, 1)
struct ThunkHeader {
    uint32_t magic_flag;     // 4 Bytes: 0xDEADBEEF
    uint32_t real_size;      // 4 Bytes: actual data size (e.g., 8388608)
    uint64_t memory_ptr;     // 8 Bytes: address of the 8MB data in Unified Memory
    uint8_t  mac_tag[16];    // 16 Bytes: AES-GCM integrity tag generated by the GPU
};
#pragma pack(pop)

static_assert(sizeof(ThunkHeader) == 32, "ThunkHeader MUST be exactly 32 bytes!");